config/routes.rb
Rails.application.routes.draw do

  kinds = %w|search laptop car mobile|

  resources :products do 
    collection do
      get '/:kind' => 'products#order', as: :order, constraints: {kind: Regexp.new(kinds.join('|'))}
    end
      resources :comments, module: :products do
    end
  end  
  
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  
  put "voices/:increase_id" => "voices#increase", :as => "voices_increase"
  put "voices/:decrease_id" => "voices#decrease", :as => "voices_decrease"

  namespace :admin do
    resources  :admins, only: [:index] 
    get "configurable/edit", as: "admin_configurable_edit"
    resources  :clients
    resources  :tasks
  end
  

  resources :infos, :messagestoadministrators, :answerfrommoderators, :orders, :line_items, :carts
  
  resources :searches do 
    collection do
      post "product" => "searches#search_product"
    end
  end

  
  get 'home/index'

  get 'store/map'
  get 'store/index'
  get 'store/all_category'
  get 'store/show'
  get 'store/contact'
  

  get 'line/increase',to: 'line_items#increase', as: :increase_line_item
  get 'line/decrease',to: 'line_items#decrease', as: :decrease_line_item
  #get 'store/showlike'
  get '/change_locale/:locale', to: 'pages#change_locale', as: :change_locale
  


  get '/users/:id/finish_signup' => 'users#finish_signup', via: [:get, :patch], :as => :finish_signup  
  get "info_show_from_email/:user_id" => "infos#show_from_email", :as => "user_show"
  get "info_show_from_navbar/:user_id" => "infos#show_from_navbar", :as => "user_show_navbar"
  get '/ban_the_user/:id' => 'admin/admins#ban_the_user', :as => 'ban'
  get '/make_admin/:id' => 'admin/admins#make_admin', :as => 'make_admin'
  delete 'user_delete/:id' => 'admin/admins#delete_user', as: "delete_user"

  root 'store#index'

end

app/views/shared/_down.html.haml
= stylesheet_link_tag 'application', params[:controller], media: 'all', 'data-turbolinks-track' => true 

= javascript_include_tag 'application',params[:controller], 'data-turbolinks-track' => true
= csrf_meta_tags 

app/views/shared/_navbar.html.erb
 
       


 <body> 
    <div class="header">

      <div class="row">


        <div class="col-md-9"> 
          
           <%unless user_signed_in?%>
          <li> <%= render "devise/registrations/new"%></li> 
          <li><%= render "devise/sessions/new"%></li>
          <li><%= render "devise/google"%></li>
          <%else%>
            <% if admin? %> 
          <li>  <%= link_to "admin", admin_admins_path%>
          </li>
          <li>  
          <%= ui_button 'destroy',  t('menu.languages.sign_out'),   destroy_user_session_path, :method => :delete  %>
          </li>
        <%end%>
          <%end %>
          <div id="site_title"><%= link_to image_tag("shop/logo.png"), root_path%></div>
            <!-- Main Menu -->
            <ol id="menu">
              <li class="active_menu_item"><%= link_to 'Category', root_path %>
                <!-- sub menu -->
                <ol>
                  <li><%= link_to 'All products', root_path %>
                  </li>
                  <li><%= link_to "Telephone", order_products_path(:mobile) %></li>
                  <li><%= link_to "Laptop",  order_products_path(:laptop)  %></li>
                  <li><%= link_to "Car",  order_products_path(:car) %></li>
                </ol>
              </li>
              <!-- END sub menu -->
              <li><a href="#">Product</a>
                <!-- sub menu -->
                <ol>
                
                  <% if user_signed_in? %>
                    <li>
                      <%= link_to 'Add product', new_product_path, data: { modal: true } %>
                    </li>
                  <% else %>
                    <li><%= link_to "Add product", new_user_registration_path
                      %> 
                    </li>
                  <% end %>
                </ol>

              </li>
              <!-- END sub menu -->

              <li><a href="#">Info</a>
                <ol>
                  <% if user_signed_in? %>
                    <li> <%= ui_button 'info',  t(:show_info),user_show_navbar_path(current_user.id)%></li>
                    <li><%= ui_button 'edit',  t(:edit_info), edit_info_path(current_user.id)%></li>
                    
                    <li><%= ui_button 'destroy',  t('menu.languages.sign_out'),   destroy_user_session_path, :method => :delete  %></li>
                    <%else%>
                      <%= ui_button 'info',  "show info",new_user_session_path %>
                      <%= ui_button 'edit',  "edit info", new_user_registration_path %>
                     <%end%>               
                </ol>
              </li>
              <!-- END sub menu -->
              <li><%= link_to "Contact", store_contact_path %></li> 
              <li><%= link_to "Map", store_map_path %></li> 

                  
         
         



            </ol>
          </div>

        
        
          
  <%# end %>

        </div>
         
          </div>  
           <div class="col-md-2">
            <%if @cart.present?%>
              <%= link_to image_tag("/assets/empty_shopping_cart.jpg", width: '72', height: '52', alt: 'Site Logo', class: "logo"), cart_path(@cart), data: { modal: true } %>
            <%end%>
      </div>
    </div>