config/routes.rb
Rails.application.routes.draw do

  kinds = %w|search laptop car mobile|

  resources :products do 
    collection do
      get '/:kind' => 'products#order', as: :order, constraints: {kind: Regexp.new(kinds.join('|'))}
    end
      resources :comments, module: :products do
    end
  end  
  
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  
  put "voices/:increase_id" => "voices#increase", :as => "voices_increase"
  put "voices/:decrease_id" => "voices#decrease", :as => "voices_decrease"

  namespace :admin do
    resources  :admins, only: [:index] 
    get "configurable/edit", as: "admin_configurable_edit"
    resources  :clients
    resources  :tasks
  end
  

  resources :infos, :messagestoadministrators, :answerfrommoderators, :orders, :line_items, :carts
  
  resources :searches do 
    collection do
      post "product" => "searches#search_product"
    end
  end

  
  get 'home/index'

  get 'store/map'
  get 'store/index'
  get 'store/all_category'
  get 'store/show'
  get 'store/contact'
  

  get 'line/increase',to: 'line_items#increase', as: :increase_line_item
  get 'line/decrease',to: 'line_items#decrease', as: :decrease_line_item
  #get 'store/showlike'
  get '/change_locale/:locale', to: 'pages#change_locale', as: :change_locale
  


  get '/users/:id/finish_signup' => 'users#finish_signup', via: [:get, :patch], :as => :finish_signup  
  get "info_show_from_email/:user_id" => "infos#show_from_email", :as => "user_show"
  get "info_show_from_navbar/:user_id" => "infos#show_from_navbar", :as => "user_show_navbar"
  get '/ban_the_user/:id' => 'admin/admins#ban_the_user', :as => 'ban'
  get '/make_admin/:id' => 'admin/admins#make_admin', :as => 'make_admin'
  delete 'user_delete/:id' => 'admin/admins#delete_user', as: "delete_user"

  root 'store#index'

end

app/views/admin/admins/_head.html.erb
      <header id="header">
      <div class="container">
       
        <button class="btn btn-responsive-nav btn-inverse" data-toggle="collapse" data-target=".nav-main-collapse">
          <i class="fa fa-bars"></i>
        </button>
      </div>
      <div class="navbar-collapse nav-main-collapse collapse">
        <div class="container">
        
          <div class="search">
      
          <form id="searchForm" action="contact.html#" method="get">
            <div class="input-group">
              <input type="text" class="form-control search" name="q" id="q" placeholder="Search..." required>
              <span class="input-group-btn">
                <button class="btn btn-default" type="submit"><i class="fa fa-search"></i></button>
              </span>
            </div>
          </form>
        </div>

      <nav class="nav-main mega-menu">
          <ul class="nav nav-pills nav-main" id="mainMenu">
            <li>
              <% if only_admin%>
                <%=link_to "Admin", admin_admins_path%>
              <%end%>
             </li>
             <li> 
              <%unless @resourse.present?%>
                <%=link_to "Home", root_path %>
              <%end%>
            </li>
   

     

            <% if user_signed_in? %>
        
            
            <li>
              <%=link_to "Setting", edit_admin_configurable_path %></li>
            <li>
              <%=link_to "Receive message", messagestoadministrators_path %></li>
            <li>
              <%=link_to "Answer", answerfrommoderators_path %>
            </li>  
            <li>
              <%=link_to "Receive Order", orders_path %>
             </li> 
             <li>
               <%#=link_to "Send message", new_message_path %>
             </li> 
         
            <li><%= link_to 'Log out',  destroy_user_session_path, :method => :delete  %></li>
        <% else %>
        <li><%= link_to "Log in", new_user_session_path
            %> 
          </li>
          <li><%= link_to "Sign up", new_user_registration_path
            %> 
          </li>
           
        <% end %>
            </ul>
            </nav>
          </div>
        </div>
        </header>

app/views/admin/admins/index.html.erb
<head>

    <% title "Admin pannel" %>
    <% meta_tag :description, "Admin panel of timeorg blog" %>
    <% meta_tag :keywords, "admin" %>
</head>
<body>
<div id="main">
  

  <div id="middle">
    
    <div id="center-column">
     
      


      
      <div class="table"> <img src="/assets/admin/bg-th-left.gif" width="8" height="7" alt="" class="left" /> <img src="/assets/admin/bg-th-right.gif" width="7" height="7" alt="" class="right" />

        <table class="listing" cellpadding="0" cellspacing="0">
          <tr>
            <th class="first" width="177">Name</th>
            <th>Email</th>
            <th>Action</th>
              <th>Role</th>
          </tr>
          <tr>

            <% @infos.each do |info| %>
              <td>
                <%= info.name %>
              </td>
              <td>
                <% if info.user.present? %>
                  <%= info.user.email %>
               
              </td>
              <td>
                <div class="btn-group closed">
                <a class="btn btn-primary" href="#"><i class="fa fa-user fa-fw"></i> User</a>
                <a class="btn btn-primary dropdown-toggle" data-toggle="dropdown" href="#">
                  <span class="fa fa-caret-down"></span></a>
                <ul class="dropdown-menu">

                  <li> 
                    <%= link_to "Show info", info_path(info.id) %>
                  </li> 

                  <li> 
                    <%= link_to "edit",edit_info_path(info) %>
                  </li>
                  
                  <li><%= link_to "delete", delete_user_path(info.id), data: { confirm: 'Are you sure?' }  %>
                  </li>      

                  <li> 
                    
                  </li> 
                  <% if info.ban==false %>
                    <li> <%= link_to "Ban", ban_path(info.id) %> </li> 
                  <% else %>
                    <li><%= link_to "Reban", ban_path(info.id) %> </li> 
                  <% end %>
                  </a></li>
                   
                  <li class="divider"></li>
                  <li><%= link_to "make admin", make_admin_path(info.id)%></li>
                </ul>

                </div>
              </dt>    
              <td>
                <%= info.user.role %>
              </td>
            </tr> 
          <% end %> 
           <%end%>  
        </table>

        <div class="select"> <strong>Other Pages: </strong>
          <select>
            <option>1</option>
          </select>
        </div>
      </div>





      <div class="table"> <img src="/assets/admin/bg-th-left.gif" width="8" height="7" alt="" class="left" /> <img src="/assets/admin/bg-th-right.gif" width="7" height="7" alt="" class="right" />
        <table class="listing form" cellpadding="0" cellspacing="0">
          <tr>
            <th class="full" colspan="2">Header Here</th>
          </tr>
          <tr>
            <td class="first" width="172"><strong>Lorem Ipsum</strong></td>
            <td class="last"><input type="text" class="text" /></td>
          </tr>
          <tr class="bg">
            <td class="first"><strong>Lorem Ipsum</strong></td>
            <td class="last"><input type="text" class="text" /></td>
          </tr>
          <tr>
            <td class="first"><strong>Lorem Ipsum</strong></td>
            <td class="last"><input type="text" class="text" /></td>
          </tr>
          <tr class="bg">
            <td class="first"><strong>Lorem Ipsum</strong></td>
            <td class="last"><input type="text" class="text" /></td>
          </tr>
        </table>
        <p>&nbsp;</p>
      </div>
    </div>

  </div>
  <div id="footer"></div>
</div>
</body>











   