config/routes.rb
Rails.application.routes.draw do

  kinds = %w|search laptop car mobile|

  resources :products do 
    collection do
      get '/:kind' => 'products#order', as: :order, constraints: {kind: Regexp.new(kinds.join('|'))}
    end
      resources :comments, module: :products do
    end
  end  
  
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  
  put "voices/:increase_id" => "voices#increase", :as => "voices_increase"
  put "voices/:decrease_id" => "voices#decrease", :as => "voices_decrease"

  namespace :admin do
    resources  :admins, only: [:index] 
    get "configurable/edit", as: "admin_configurable_edit"
    resources  :clients
    resources  :tasks
  end
  

  resources :infos, :messagestoadministrators, :answerfrommoderators, :orders, :line_items, :carts
  
  resources :searches do 
    collection do
      post "product" => "searches#search_product"
    end
  end

  
  get 'home/index'

  get 'store/map'
  get 'store/index'
  get 'store/all_category'
  get 'store/show'
  get 'store/contact'
  

  get 'line/increase',to: 'line_items#increase', as: :increase_line_item
  get 'line/decrease',to: 'line_items#decrease', as: :decrease_line_item
  #get 'store/showlike'
  get '/change_locale/:locale', to: 'pages#change_locale', as: :change_locale
  


  get '/users/:id/finish_signup' => 'users#finish_signup', via: [:get, :patch], :as => :finish_signup  
  get "info_show_from_email/:user_id" => "infos#show_from_email", :as => "user_show"
  get "info_show_from_navbar/:user_id" => "infos#show_from_navbar", :as => "user_show_navbar"
  get '/ban_the_user/:id' => 'admin/admins#ban_the_user', :as => 'ban'
  get '/make_admin/:id' => 'admin/admins#make_admin', :as => 'make_admin'
  delete 'user_delete/:id' => 'admin/admins#delete_user', as: "delete_user"

  root 'store#index'

end

app/models/cart.rb
class Cart < ActiveRecord::Base
  
  before_destroy :order_present	
  has_many :line_items, dependent: :destroy


  def add_product(product)
    current_item = line_items.find_by(product)
	if current_item
	  current_item.quantity += 1
	else
	  current_item = line_items.build(product)
	end
	current_item 
  end
  
  def order_present	
    line_items.each do |line| 
      if line.order_id.present?
     	return false
      else 
      	return true
      end
    end
  end	

  def total_price
    line_items.to_a.sum {|item| item.total_price}
  end

end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  
  include ControllerRails  
  before_action :set_cart, only: [ :show, :edit, :update, :destroy]
  #before_action :define_eccept, only: [:edit, :update, :destroy]
  
  respond_to :html, :js, :json
  rescue_from ActiveRecord::RecordNotFound, with: :invalid_cart
  
  def set_model
    @model=Cart
  end 

  def show
    respond_modal_with @cart
  end

  def destroy
    @cart.destroy if @cart.id==session[:cart_id]
    session[:cart_id]=nil
    @cart.destroy
    respond_to do |format|
      format.html { redirect_to root_path, notice: 'Cart was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  
    def cart_params
      params[:cart]
    end

end

app/helpers/carts_helper.rb
module CartsHelper

   
end

app/views/carts/_cart.html.erb
  <%= render "line_items/line_item"%>



  Total price:
  <dt class="total_cell"> 
    <%= all_total_price %>
  </dt>




  <dt>
<%= ui_button 'destroy',  t(:Delete), cart_path(@cart), method: :delete, :data => { :confirm => 'Are you sure?' } %>

<% if @cart.present? %>
<%= ui_button 'add',  t(:add), new_order_path %> 
<% end %>
<%= ui_button 'back',  t(:back), :back %>
</dt>

app/views/carts/_form.html.haml
= form_for @cart do |f|
  = errors_for(@cart)

  .actions
    = f.submit 'Save'

app/views/carts/edit.html.haml
%h1 Editing cart

= render 'form'

= link_to 'Show', @cart
\|
= link_to 'Back', carts_path

app/views/carts/index.html.haml
%h1 Listing carts

%table
  %thead
    %tr
      %th
      %th
      %th

  %tbody
    - @carts.each do |cart|
      %tr
        %td= link_to 'Show', cart
        %td= link_to 'Edit', edit_cart_path(cart)
        %td= link_to 'Destroy', cart, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Cart', new_cart_path

app/views/carts/new.html.haml
%h1 New cart

= render 'form'

= link_to 'Back', carts_path

app/views/carts/show.html.erb
<% if notice %>
<p id="notice"><%= notice %></p>
<% end %>



<%= render @cart %>